[package]
name = "MedVault"
version = "1.0.0"
authors = ["MedVault Team"]

[addresses]
medvault = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
